name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      statuses: write
      checks: write
      contents: write
      pages: write
      id-token: write

    steps:
    - name: Checkout Web App Code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Build Web App
      run: dotnet build

    - name: Start Web App in Background
      run: |
        dotnet run --no-build &
        echo "Web App started in the background."
      env:
        ASPNETCORE_ENVIRONMENT: Development

    - name: Wait for Web App to be ready
      run: |
        timeout 30 bash -c 'until curl -s http://localhost:5130/ > /dev/null; do sleep 1; done'
        echo "Web App is up and running."

    - name: Checkout Playwright Tests Code
      uses: actions/checkout@v4
      with:
        repository: nishant7956/EcommerceAutomationPlaywright
        path: 'tests'

    - name: Build Playwright Tests
      run: dotnet build ECommerce.Playwright.slnx
      working-directory: ./tests

    - name: Install Playwright Browsers
      run: pwsh tests/ECommerce.Playwright.Tests/bin/Debug/net8.0/playwright.ps1 install --with-deps

    - name: Run Playwright Tests (Smoke)
      run: dotnet test ECommerce.Playwright.slnx --filter "Category=Smoke" --logger:"trx" --results-directory ./TestResults
      working-directory: ./tests
      env:
        DOTNET_ENVIRONMENT: CI

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: ./tests/TestResults/

    - name: Collect Allure Results
      if: always()
      run: |
        mkdir -p tests/TestResults/allure-results
        # Find all allure-results folders in the bin directories and copy their contents
        find tests -type d -path "*/bin/*/allure-results" -exec cp -r {}/* tests/TestResults/allure-results/ \; || true

    - name: Generate Allure Report
      uses: simple-elf/allure-report-action@master
      if: always()
      with:
        allure_results: tests/TestResults/allure-results
        gh_pages: gh-pages
        allure_report: allure-report
        allure_history: allure-history

    - name: Deploy Allure Report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: allure-history
