name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      statuses: write
      checks: write

    steps:
    - name: Checkout Web App Code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Build Web App
      run: dotnet build

    - name: Start Web App in Background
      run: |
        dotnet run --no-build &
        echo "Web App started in the background."
      env:
        ASPNETCORE_ENVIRONMENT: Development

    - name: Wait for Web App to be ready
      run: |
        timeout 30 bash -c 'until curl -s http://localhost:5130/ > /dev/null; do sleep 1; done'
        echo "Web App is up and running."

    - name: Checkout Playwright Tests Code
      uses: actions/checkout@v4
      with:
        repository: nishant7956/EcommerceAutomationPlaywright
        path: 'tests'

    - name: Build Playwright Tests
      run: dotnet build ECommerce.Playwright.slnx
      working-directory: ./tests

    - name: Install Playwright Browsers
      run: pwsh tests/ECommerce.Playwright.Tests/bin/Debug/net8.0/playwright.ps1 install --with-deps

    - name: Run Playwright Tests
      run: dotnet test ECommerce.Playwright.slnx --logger:"trx;LogFileName=test_results.trx" --results-directory ./TestResults
      working-directory: ./tests
      env:
        DOTNET_ENVIRONMENT: CI

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: ./tests/TestResults/

    - name: Publish Test Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Playwright Test Results
        path: "tests/TestResults/**/*.trx"
        reporter: dotnet-trx
        fail-on-error: false
